export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token';
export const ACCESS_KEY = 'tSyFRy8IWSysaujA0vdZnJywv6tJ41_rf7UzFE41PL0';
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize';
export const REDIRECT_URI = 'http://127.0.0.1:5500';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';
export const SECRET_KEY = 'O2NvQSRo5Ci5lRYhyoWEcoM5HHsicmQdd6Wh6hsE8nE';